### ISSUE TITLE
prime icon not working

### ISSUE THREAD

**Issue by Jogai** [antfu/unplugin-icons#194] opened 2022-05-03 15:36 UTC
Set up the project as described in the readme. Including auto import: https://github.com/antfu/unplugin-icons#auto-importing

The important part of vite.config.js:

    // https://github.com/antfu/unplugin-auto-import
    AutoImport({
      imports: ["vue", "vue/macros", "vue-router", "@vueuse/core"],
      dts: true,
      eslintrc: {
        enabled: true
      }
    }),

    // https://github.com/antfu/unplugin-icons
    Icons({
      compiler: "vue3",
      autoInstall: true
    }),

    // https://github.com/antfu/vite-plugin-components
    Components({
      dts: true,
      resolvers: [IconsResolver()]
    }),

    // https://github.com/nabla/vite-plugin-eslint
    eslintPlugin(),

Several icons work, and I see vite installing the sets I choose, but the prime icons wont work.

    <i-ph-sign-out-fill /> //<- works
    <i-prime-sign-out /> //<- broken

**Comment by userquin** [comment] 2022-05-03 16:46
try adding `enabledCollections: ['prime'],` to the `IconsResolver`

**Comment by Jogai** [comment] 2022-05-03 17:33
Thanks, but no. Works for other sets tough. And `"@iconify-json/prime": "^1.1.1",` is added to my packages.json I saw, but its not displayed.

**Comment by WormGirl** [comment] 2023-05-29 08:45
mee to , i use the set of  ion, Most of the icons can be used normally, but some icon not work, like ~icons/ion/document-text-outline, this got 404

**Comment by antfu** [comment] 2023-05-29 08:56
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-05-29 08:56 UTC
