### ISSUE TITLE
Can't change icon color(Vue 3 Vite)

### ISSUE THREAD

**Issue by onurusluca** [antfu/unplugin-icons#201] opened 2022-05-17 06:17 UTC
Hi!

While using unplugin-icons with Vue 3 and Vite with composition API Script Setup, I can't change the color.
I can change the size with no problem though.
Here is the code:

```
     <carbon-checkmark-outline
        class="toast-icon"
        style="font-size: 2rem; color: red"
      />
```

Vite config:

```
      IconsResolver({
          prefix: false,
          enabledCollections: ["carbon"],
        })
```

**Comment by antfu** [comment] 2022-05-17 06:18
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-05-17 06:18 UTC

**Comment by onurusluca** [comment] 2022-05-17 06:20
@antfu Thanks for the reply,
No need for reproduction. I didn't do any changes. I am using the code from the documentation.
Is it possible to change the color with Vue 3 and Vite currently?

**Comment by antfu** [comment] 2022-05-17 06:22
https://github.com/antfu/unplugin-icons/tree/main/examples

**Comment by mgutz** [comment] 2022-06-13 13:14
@onurusluca and any other who might run into this issue

Some of the svg icons have hardcoded values, like stroke, so they are not easily overridden. Try an icon from another family.

**Comment by coderwyd** [comment] 2023-02-17 07:06
@antfu When there are width and height attributes in svg itself, the size cannot be modified by font-size, how should I do it?
![image](https://user-images.githubusercontent.com/53386850/219573413-4d37f2c1-eb84-4da9-a749-cb3a294a9fa6.png)

**Comment by JACKZGGG** [comment] 2024-05-14 09:01
> @antfu When there are width and height attributes in svg itself, the size cannot be modified by font-size, how should I do it? ![image](https://user-images.githubusercontent.com/53386850/219573413-4d37f2c1-eb84-4da9-a749-cb3a294a9fa6.png)

I suggest you take a look at your SVG, it may already be set up inside

**Comment by coderwyd** [comment] 2024-05-14 09:58
> I suggest you take a look at your SVG, it may already be set up inside

Yes, I understood it wrong.
