### ISSUE TITLE
 material-symbols 无法自动导入

### ISSUE THREAD

**Issue by Aerolii** [antfu/unplugin-icons#205] opened 2022-05-28 16:54 UTC
material-symbols 图标无法自动导入

**Comment by webxmsj** [comment] 2022-06-10 04:02
同样遇到了这个问题

**Comment by antfu** [comment] 2022-06-16 09:18
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-06-16 09:18 UTC

**Comment by levidavidmurray** [comment] 2022-08-11 21:29
I ran into this issue as well. I just had to update my `@iconify/json` and `unplugin-icons` versions. `material-symbols` was missing from whatever version I was on.
